name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0

  upload-sql:
    needs: pre-commit
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - run: ./scripts/upload_sql_data.py
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        ARTICLES_SITE: ${{ secrets.ARTICLES_SITE }}
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
