# todo: not actually pre commit
name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0

  upload-sql:
    needs: pre-commit
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - uses: tj-actions/changed-files@v34
      id: changed-files
      with:
        files: |
          data/**
          scripts/upload_sql_data.py

    - name: Install SSH key
      if: steps.changed-files.outputs.any_changed == 'true' || github.run_attempt > 1
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PIP_SSH_KEY }}
        known_hosts: unnecessary

    - uses: actions/setup-python@v3
      if: steps.changed-files.outputs.any_changed == 'true' || github.run_attempt > 1
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - run: pip install -r requirements.txt
      if: steps.changed-files.outputs.any_changed == 'true' || github.run_attempt > 1

    - run: ./scripts/upload_sql_data.py
      if: steps.changed-files.outputs.any_changed == 'true' || github.run_attempt > 1
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        ARTICLES_SITE: ${{ secrets.ARTICLES_SITE }}
        DATABASE_URI: ${{ secrets.DATABASE_URI }}
